### ISSUE TITLE
How to recover the original coordinates

### ISSUE THREAD

**Issue by balazsdukai** [cityjson/Blender-CityJSON-Plugin#7]
It seems that the plugin (master branch) centers the objects around 0,0,0. I have a coordinate in the citymodel's original coordinate system which I want to locate in the model, how can I do that?

**Comment by konmast3r** [comment]
If you install the plugin from the develop branch, which is currently many commits ahead from master, the importer has been improved and now stores the X,Y, Z translation, as custom properties of the world object of Blender. 

If you have your original CRS coordinates, just add the X,Y,Z translation (algebraically) to them and you should get the point's coordinates in Blender's model. 

In the screenshot below you can see how to find the translation through Blender's interface.
Hope it helps!

![Screenshot from 2020-01-30 14-16-24](https://user-images.githubusercontent.com/34276408/73453512-749a0000-436c-11ea-86c0-4d0f9194b13d.png)

**Comment by balazsdukai** [comment]
Yes, thanks!
